name: lukens
description: Lukens - Proposal & SOW Builder
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.20.2
  url_launcher: ^6.1.10
  web: ^1.1.1
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  signature: ^6.3.0
  google_fonts: ^8.0.1
  flutter_riverpod: ^3.2.1
  file_picker: ^10.3.10
  image_picker: ^1.0.4
  cloudinary_flutter: ^1.3.0
  dio: ^5.3.1
  flutter_reorderable_list: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
